version: "3.7"
services:
  web:
    build:
      args:
        user: skillsheet-server
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: skillsheet-server
    container_name: skillsheet-server-web
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - skillsheet-server

  db:
    image: mysql:8.0
    container_name: skillsheet-server-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - '${APP_PORT:-3306}:3306'
    networks:
      - skillsheet-server

  nginx:
    image: nginx:alpine
    container_name: skillsheet-server-nginx
    restart: unless-stopped
    ports:
      - '${APP_PORT:-8000}:80'
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - skillsheet-server

networks:
  skillsheet-server:
    driver: bridge
volumes:
   db:
    driver: local